name:  Print Hello World 
on:  
  push:  
jobs:
    print:
        runs-on: macOS-latest
        defaults:
            run:
                working-directory: backend
        steps: 
            - name: Repo Cloning 
              uses: actions/checkout@v4
            - name: install dependencies 
              run : npm ci
            -  name:  run test
               run : npm test